### ISSUE TITLE
How to get the labels of BVCC test wav?

### ISSUE THREAD

**Issue by jiusansan222** [unilight/LDNet#1]
How can I get BVCC test dataset? I only found data and label of train and val in VoiceMOS codalab, but I don't know how to get the labels of test wav. Is it opensource?

**Comment by unilight** [comment]
Hi @jiusansan222,

We are preparing an all-in-one package containing all the materials of the VoiceMOS Challenge 2022, including the ground truth labels of the test set. We will support instructions on how to access the labels and perform evaluation once it is released.

**Comment by jiusansan222** [comment]
Has the dataset been released yet? The codalab competition website doesn't seem to work, is there any other method to get the labels? Could you E-mail me a copy? Thanks!

**Comment by unilight** [comment]
I recommend to use this script to get the data: https://github.com/unilight/sheet/blob/main/egs/bvcc/local/data_download.sh
