### ISSUE TITLE
Expected 4 got 3 

### ISSUE THREAD

**Issue by AI4VTV** [unilight/LDNet#2]
[Info] Use mean listener: False
[Info] Model parameters: 1386198
Train: 100% 845/845 [06:23<00:00,  2.20 step/s]tep/s, loss=4.78, mean_loss=1.32, LD_loss=0.866] 
Valid:   0% 0/3000 [00:01<?, ? step/s],  2.46 step/s, loss=6.95, mean_loss=1.48, LD_loss=1.37]  
Train:  18% 154/845 [01:26<06:29,  1.77 step/s]
Traceback (most recent call last):p/s]
  File "train.py", line 269, in <module>
    main()
  File "train.py", line 265, in main
    valid(config["inference_mode"], model, valid_loader, valid_set.systems, save_dir, global_step, "Valid")
  File "train.py", line 36, in valid
    mag_sgrams_padded, avg_scores, sys_names, wav_names = batch
ValueError: not enough values to unpack (expected 4, got 3)
Overall:   2% 999/50000 [07:50<6:24:29,  2.12 step/s, loss=6.95, mean_loss=1.48, LD_loss=1.37]

While running python train.py --config configs/MBNet.yaml --tag model1

**Comment by unilight** [comment]
Sorry for this super late reply... if you are still interested in this research, please try to use this new toolkit I wrote: https://github.com/unilight/sheet and open issues there if you find trouble using it!
